website/views.py
import re
import pymongo
from logger import Logger
from .models import mongo
from .user import get_user
from .constants import views_constants
from flask_login import login_required, current_user
from flask import Blueprint, flash, redirect, render_template, url_for, request

logger = Logger(mongo)
views = Blueprint("views", __name__)


@views.route("/home")
def home():
    return render_template("home.html", user=current_user)


@views.route("/")
@login_required
def profile():
    current_user.update_rating()
    return render_template("profile.html", user=current_user)


@views.route("/public_profile/<username>")
def public_profile(username):
    if not username:
        flash("Please enter a username", category="error")
        return redirect(url_for("view.profile"))

    friend = get_user(username=username)
    if friend is None:
        flash("User does not exist.", category="error")
        return redirect((url_for("views.profile")))

    return render_template("public_profile.html", user=current_user, friend=friend)


@views.route("/search", methods=["POST"])
def search():
    username = request.form.get("username")
    if not username:
        flash("Enter a username", category="error")
        # redirect_url = "views." + re.findall(r"\/([A-Z]*[a-z]*)\?*", request.referrer)[-1]
        # return redirect(url_for(redirect_url))
        return redirect(url_for("views.profile"))

    users_collection = mongo.db.users
    user_list = list(
        users_collection.find(
            {
                "$or": [
                    {"_id": username},
                    {"github_username": username},
                    {"codechef_username": username},
                    {"codeforces_username": username},
                    {"full_name": re.compile(username, re.IGNORECASE)},
                ]
            },
            {
                "_id": 1,
                "github_username": 1,
                "codechef_username": 1,
                "codeforces_username": 1,
                "score": 1,
            },
        )
    )

    return render_template("search.html", user_list=user_list, user=current_user)


@views.route("/leaderboard")
def leaderboard():
    global_leaderboard = get_global_leaderboard()
    friends_leaderboard = get_friend_leaderboard()

    return render_template(
        "leaderboard.html",
        user=current_user,
        global_leaderboard=global_leaderboard,
        friends_leaderboard=friends_leaderboard,
    )


def get_global_leaderboard():
    leaderboard = []
    users_collection = mongo.db.users
    for user in users_collection.find().sort("score", pymongo.DESCENDING):
        leaderboard.append((user["_id"], user.get("score", 0)))
    return leaderboard


def get_friend_leaderboard():
    if not current_user.is_authenticated:
        return [("Sign-In to view your personal leaderboard", "")]

    leaderboard = [(current_user.username, current_user.score)]

    users_collection = mongo.db.users
    for friend_username in current_user.friends:
        friend = users_collection.find_one({"_id": friend_username})
        if friend:
            leaderboard.append((friend["_id"], friend.get("score", 0)))
        else:
            users_collection.delete_one({"_id": friend_username})
    leaderboard.sort(key=lambda x: x[-1], reverse=True)
    return leaderboard

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/about_stylesheet.css') }}" />
    {% block head %}
    {% endblock %}
</head>

<body>
    <div class="body_container">

        <!-- Nav Bar -->
        <nav class="navbar">
            <span><a href="/home">OUTLIERS.</a></span>
            <ul>
                <li><a href="/home">Home</a></li>
                <li><a href="/leaderboard">Leaderboard</a></li>

                {% if user.is_authenticated %}
                <li><a href="/">My-Profile</a></li>
                <li><a href="/logout">Sign-Out</a></li>
                {% else %}
                <li><a href="/login">Sign-In</a></li>
                {% endif %}
            </ul>

            <form action="{{ url_for('views.search') }}" , method="post">
                <input type="text" name="username" id="public_search_uname" placeholder="Name or Username...">
                <button type="submit" id="public_submit"><i class="fa fa-search" aria-hidden="true"
                        style="font-size:20px;"></i></button>
            </form>
        </nav>


        <!-- Flash Messages -->
        <!-- {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% endwith %} -->

        {% block body %}
        {% endblock %}
    </div>
</body>

website/templates/home.html
{% extends "base.html" %} {% block head %}
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<title>OUTLIERS</title>
{% endblock %} {% block body %}
<div id="body_head">
  <div id="body_about_text">
    <div id="body_about_text_out">
      <div id="body_about_text_heading">
        <span>Social Coding Experience.</span>
      </div>
      <div id="body_about_text_button">
        <form action="https://github.com/Mizan-Ali/OUTLIERS_1" target="popup">
          <input type="submit" value="Github" id="" />
        </form>
        <form
          action="https://docs.google.com/presentation/d/1cczDgtSutDv_qQWtzmlOQbSoqLEOguwF/edit#slide=id.g11f60460301_1_10"
          target="popup"
        >
          <input type="submit" value="Project Details" id="" />
        </form>
      </div>
    </div>
  </div>
  <div id="body_about_head"></div>
</div>
<hr />

<div id="body_about" class="about_outliers">
  <div id="body_about_info">
    <span id="body_about_info_head">About</span>
    <div id="body_about_info_text">
      <p>
        Being a coder, you don’t want to spend your time jumping from one site
        to another to track your progress along with your peers.
      </p>
      <p>
        The Social Coding Experience offers a one stop destination to track your
        progress across various coding platforms.
      </p>
      <p>
        Add your various coding profiles and see where you stand among your
        peers! Brag about your score on social media platforms and get in the
        eyes of potential recruiters.
      </p>
    </div>
  </div>
</div>

<hr />

<div class="team_outliers" id="body_team">
  <div id="body_team_heading">
    <span>Meet the team</span>
  </div>
  <div id="body_team_body">
    <!-- -----Team Mate - 1----- -->
    <div class="body_team_card">
      <div class="body_team_card_dp">
        <img
          src="../static/images/jayesh.jfif"
          alt="Team Mate : Jayesh Rohan Singh"
        />
      </div>
      <hr />
      <div class="body_team_card_info">
        <div class="team_name">
          <span>Jayesh Rohan Singh</span>
        </div>
        <div class="team_work">
          <span>Intern SWE @ Red Hat</span>
        </div>
        <div class="team_role">
          <span
            ><strong>Role: </strong> Backend Development and Database
            Integration</span
          >
        </div>
        <div class="team_contact">
          <a href="https://github.com/Conero007" target="_blank"
            ><img
              src="{{ url_for('static', filename='images/github.png') }}"
              alt="github"
          /></a>
          <a
            href="https://www.linkedin.com/in/jayesh-rohan-singh/"
            target="_blank"
            ><img
              src="{{ url_for('static', filename='images/linkedin.png') }}"
              alt="linkedin"
          /></a>
        </div>
      </div>
    </div>
    <!-- -----Team Mate - 2----- -->
    <div class="body_team_card">
      <div class="body_team_card_dp">
        <img
          src="../static/images/mizan.jpg"
          alt="Team Mate : Mohd Mizan Ali"
        />
      </div>
      <hr />
      <div class="body_team_card_info">
        <div class="team_name">
          <span>Mohd Mizan Ali</span>
        </div>
        <div class="team_work">
          <span>Power Intern @ Infosys</span>
        </div>
        <div class="team_role">
          <span
            ><strong>Role: </strong>Backend Development and API
            Integration</span
          >
        </div>
        <div class="team_contact">
          <a href="https://github.com/Mizan-Ali" target="_blank"
            ><img
              src="{{ url_for('static', filename='images/github.png') }}"
              alt="github"
          /></a>
          <a href="https://www.linkedin.com/in/mohd-mizan-ali/" target="_blank"
            ><img
              src="{{ url_for('static', filename='images/linkedin.png') }}"
              alt="linkedin"
          /></a>
        </div>
      </div>
    </div>
    <!-- -----Team Mate - 3----- -->
    <div class="body_team_card">
      <div class="body_team_card_dp">
        <img
          src="../static/images/prateek_bajpai.jfif"
          alt="Team Mate : Prateek Bajpai"
        />
      </div>
      <hr />
      <div class="body_team_card_info">
        <div class="team_name">
          <span>Prateek Bajpai</span>
        </div>
        <div class="team_work">
          <span>Intern, Development @ Commvault</span>
        </div>
        <div class="team_role">
          <span
            ><strong>Role: </strong> Backend Development and API
            Development</span
          >
        </div>
        <div class="team_contact">
          <a href="https://github.com/prateekbajpaiCS" target="_blank"
            ><img
              src="{{ url_for('static', filename='images/github.png') }}"
              alt="github"
          /></a>
          <a
            href="https://www.linkedin.com/in/prateekbajpaicse/"
            target="_blank"
            ><img
              src="{{ url_for('static', filename='images/linkedin.png') }}"
              alt="linkedin"
          /></a>
        </div>
      </div>
    </div>
    <!-- -----Team Mate - 4----- -->
    <div class="body_team_card">
      <div class="body_team_card_dp">
        <img
          src="../static/images/siddharth.jfif"
          alt="Team Mate : Siddharth Sharma"
        />
      </div>
      <hr />
      <div class="body_team_card_info">
        <div class="team_name">
          <span>Siddharth Sharma</span>
        </div>
        <div class="team_work">
          <span>Software Engineer @ Apisero</span>
        </div>
        <div class="team_role">
          <span><strong>Role: </strong>Frontend and Backend Development</span>
        </div>
        <div class="team_contact">
          <a href="https://github.com/siddharthSharma102" target="_blank"
            ><img
              src="{{ url_for('static', filename='images/github.png') }}"
              alt="github"
          /></a>
          <a
            href="https://www.linkedin.com/in/siddharth-sharma102/"
            target="_blank"
            ><img
              src="{{ url_for('static', filename='images/linkedin.png') }}"
              alt="linkedin"
          /></a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/leaderboard.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/leaderboard_stylesheet.css') }}">
<title>Leaderboard</title>
{% endblock %}

{% block body %}

<div class="dashboard">
    <div class="left_div">
        <p>
            Friends Leaderboard
        </p>
        <div class="leaderboard_list">
            <div class="friend_headers">
                <div class="friend_labels">
                    <span>Username</span>
                    <span>-</span>
                    <span>Score</span>
                </div>
            </div>
            <div class="friends_data">
                {% for user in friends_leaderboard %}
                <div class="friend_data_inner"
                    onclick="location.href='{{ url_for('''views.public_profile''', username=user[0]) }}'"
                    style="cursor:pointer;">
                    <div class="friend_labels_data">
                        <span>{{ user[0] }}</span>
                        <span>-</span>
                        <span>{{ user[1] }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="division"></div>
    <div class="left_div">
        <p>
            Global Leaderboard
        </p>
        <div class="leaderboard_list">
            <div class="friend_headers">
                <div class="friend_labels">
                    <span>Username</span>
                    <span>-</span>
                    <span>Score</span>
                </div>
            </div>
            <div class="friends_data">
                {% for user in global_leaderboard %}
                <div class="friend_data_inner"
                    onclick="location.href='{{ url_for('''views.public_profile''', username=user[0]) }}'"
                    style="cursor:pointer;">
                    <div class="friend_labels_data">
                        <span>{{ user[0] }}</span>
                        <span>-</span>
                        <span>{{ user[1] }}</span>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block head %}
<title>Sign In</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/login_style.css') }}" />
{% endblock %}

{% block body %}
<div class="out_box">
  <div class="in_box">
    <form method="POST">
      <input type="_id" class="form-control" id="_id" name="_id" placeholder="email/username" />
      <input type="password" class="form-control" id="password" name="password" placeholder="password" />
      <button type="submit" class="btn">Login</button>
      <span style="margin-top: 30px">_____________________________</span>
    </form>
    <div class="sign_up">
      <span>Not registered yet? </span><a href="/signup">SIGN UP</a>
    </div>
  </div>
</div>
{% endblock %}

website/templates/profile.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/profile_stylesheet.css') }}" />
<title>OUTLIERS</title>
{% endblock %}

{% block body %}
<div class="dashboard">
  <div class="left_div">
    <div class="details">
      <div class="profile_parent">
        <a href = "{{ user.profile_pic }}"><img src="{{ user.profile_pic }}" alt="" /></a>
        <a href="https://gravatar.com/" target="_blank">
          <i class="fa fa-pencil-square-o" aria-hidden="true" title="Edit Profile Pic on Gravatar"></i>
        </a>
      </div>
      <span>{{ user.full_name }}</span>
      <p>({{ user.username }})</p>
      <p>{{ user.occupation }}</p>
      <hr />
      <p>Score - {{ user.score }}</p>
      <!-- <p>Global Ranking - NULL</p> -->
      <p>Upvotes - {{ user.upvotes }} | Downvotes - {{ user.downvotes }}</p>
      <hr />
      <p>Gender - {{ user.gender }}</p>
      <!-- <p>Followers - NULL </p> -->
    </div>
    <div class=""></div>
  </div>
  <div class="right_div">
    <div class="github_card">
      <div class="github_uname">
        <img src="../static/images/github.png" alt="Github" />
        {% if user.github_username %}
        <a href="https://github.com/{{ user.github_username }}" target="_blank">{{ user.github_username }}</a>
        <form action="{{ url_for('modify.remove_github') }}" method="post">
          <button type="submit" class="github_remove" title="Unlink Account">
            <i class="fa fa-trash" aria-hidden="true" style="color: red; font-size: 24px"></i>
          </button>
        </form>
        <form action="{{ url_for('modify.refresh_github') }}" method="post">
          <button type="submit" class="github_remove" title="Refresh Data">
            <i class="fa fa-refresh" aria-hidden="true" style="color: green; font-size: 24px"></i>
          </button>
        </form>
        {% else %}
        <form action="{{ url_for('modify.add_github') }}" method="post">
          <input type="text" name="github_username" class="github_search_uname" placeholder="Github Username...." />
          <button type="submit" class="github_submit">
            <i class="fa fa-plus" aria-hidden="true" style="font-size: 24px"></i>
          </button>
        </form>
        {% endif %}
      </div>
      <div class="github_info">
        {% if user.github_username %}
        <div class="github_stars common">
          <span>Stars: {{ user.github_data.stargazers_count }}</span>
        </div>
        <div class="github_forks common">
          <span>Forks: {{ user.github_data.forks_count }}</span>
        </div>
        <div class="github_total_follower common">
          <span>Total Followers: {{ user.github_data.followers }}</span>
        </div>
        <div class="github_contri common">
          <span>Contributions Last Year: {{ user.github_data.total_commits }}</span>
        </div>
        {% else %}
        <h3 style="padding-left: 70vh; padding-top: 7vh; font-size: 25px; font-weight: bold;">(Not Available)</h3>
        {% endif %}
      </div>
    </div>

    <!-- -----codechef info----- -->
    <div class="codechef_card">
      <div class="codechef_uname">
        <img src="../static/images/code-chef.png" alt="Codechef" />
        {% if user.codechef_username %}
        <a href="https://www.codechef.com/users/{{ user.codechef_username }}" target="_blank">{{ user.codechef_username
          }}</a>
        <form action="{{ url_for('modify.remove_codechef') }}" method="post">
          <button type="submit" class="codechef_remove" title="Unlink Account">
            <i class="fa fa-trash" aria-hidden="true" style="color: red; font-size: 24px"></i>
          </button>
        </form>
        <form action="{{ url_for('modify.refresh_codechef') }}" method="post">
          <button type="submit" class="codechef_remove" title="Refresh Data">
            <i class="fa fa-refresh" aria-hidden="true" style="color: green; font-size: 24px"></i>
          </button>
        </form>
        {% else %}
        <form action="{{ url_for('modify.add_codechef') }}" method="post">
          <input type="text" name="codechef_username" class="codechef_search_uname"
            placeholder="Codechef Username...." />
          <button type="submit" class="codechef_submit">
            <i class="fa fa-plus" aria-hidden="true" style="font-size: 24px"></i>
          </button>
        </form>
        {% endif %}
      </div>
      <div class="codechef_info">
        {% if user.codechef_username %}
        <div class="codechef_cur_rating common">
          <span>Country: {{ user.codechef_data.country }}</span>
        </div>
        <div class="codechef_stars common">
          <span>Stars: {{ user.codechef_data.num_stars }}</span>
          <!-- <div class="codechef_stars_img">
                        <img src="{{ url_for('static', filename='images/star.png') }}" alt="rating">
                        <img src="{{ url_for('static', filename='images/star.png') }}" alt="rating">
                        <img src="{{ url_for('static', filename='images/star.png') }}" alt="rating">
                        <div style="width:15px;height:30px;overflow:hidden;">
                            <img src="{{ url_for('static', filename='images/star.png') }}" alt="rating">
                        </div>
                    </div> -->
        </div>
        <div class="codechef_cur_rating common">
          <span>Current Rating: {{ user.codechef_data.rating }}</span>
        </div>
        <div class="codechef_high_rating common">
          <span>Highest Rating: {{ user.codechef_data.highest_rating }}</span>
        </div>
        <div class="codechef_country_ranking common">
          <span>Country Ranking: {{ user.codechef_data.country_rank }}</span>
        </div>
        <div class="codechef_g_Ranking common">
          <span>Global Ranking: {{ user.codechef_data.global_rank }}</span>
        </div>
        {% else %}
        <h3 style="padding-left: 70vh; padding-top: 10vh; font-size: 25px; font-weight: bold;">(Not Available)</h3>
        {% endif %}
      </div>
    </div>

    <!-- -----codeforces info----- -->
    <div class="codechef_card">
      <div class="codechef_uname">
        <img src="../static/images/code-forces.png" alt="Codeforces" />
        {% if user.codeforces_username %}
        <a href="https://codeforces.com/profile/{{ user.codeforces_username }}" target="_blank">{{
          user.codeforces_username }}</a>
        <form action="{{ url_for('modify.remove_codeforces') }}" method="post">
          <button type="submit" class="codechef_remove" title="Unlink Account">
            <i class="fa fa-trash" aria-hidden="true" style="color: red; font-size: 24px"></i>
          </button>
        </form>
        <form action="{{ url_for('modify.refresh_codeforces') }}" method="post">
          <button type="submit" class="codechef_remove" title="Refresh Data">
            <i class="fa fa-refresh" aria-hidden="true" style="color: green; font-size: 24px"></i>
          </button>
        </form>
        {% else %}
        <form action="{{ url_for('modify.add_codeforces') }}" method="post">
          <input type="text" name="codeforces_username" class="codechef_search_uname"
            placeholder="Codeforces Username...." />
          <button type="submit" class="codechef_submit">
            <i class="fa fa-plus" aria-hidden="true" style="font-size: 24px"></i>
          </button>
        </form>
        {% endif %}
      </div>
      <div class="codechef_info">
        {% if user.codeforces_username %}
        <div class="codechef_ranking common">
          <span>Ranking: {{ user.codeforces_data.rank }}</span>
        </div>
        <div class="codechef_cur_rating common">
          <span>Current Rating: {{ user.codeforces_data.rating }}</span>
        </div>
        <div class="codechef_high_rating common">
          <span>Highest Rating: {{ user.codeforces_data.highest_rating }}</span>
        </div>
        <div class="codechef_total_probs common">
          <span>Total Problem Solved: {{ user.codeforces_data.problems_solved
            }}</span>
        </div>
        {% else %}
        <h3 style="padding-left: 70vh; padding-top: 10vh; font-size: 25px; font-weight: bold;">(Not Available)</h3>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/search.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/search_stylesheet.css') }}">
<title>Search</title>
{% endblock %}

{% block body %}
<div class="dashboard">
    <div class="out_box">
        <div class="search_in">
            <form action="{{ url_for('views.search') }}" method="post">
                <input type="text" name="username" id="search_uname" placeholder="Enter Username">
                <input type="submit" name="submit_btn" id="submit_btn" value="Submit">
            </form>
        </div>
        <div class="search_results">
            {% for user in user_list %}
            <div class="search_card"
                onclick="location.href='{{ url_for('''views.public_profile''', username=user._id) }}'"
                style="cursor:pointer;">
                <div class="card_top">
                    <div class="info">
                        <span style="font-size: 25px; font-weight: bold; padding-right: 15px;">OUTLIERS. </span>
                        <p>{{ user._id }}</p>
                    </div>
                    <div style="width: 0px; height: 85%;border: 1px solid black;"></div>
                    <div class="info">
                        <img src="{{ url_for('static', filename='images/github.png') }}" alt="">
                        {% if user.github_username %}
                        <p>{{ user.github_username }}</p>
                        {% else %}
                        <p>(Not Available)</p>
                        {% endif %}
                    </div>
                </div>
                <div class="division"></div>
                <div class="card_top">
                    <div class="info">
                        <img src="{{ url_for('static', filename='images/code-chef.png') }}" alt="">
                        {% if user.codechef_username %}
                        <p>{{ user.codechef_username }}</p>
                        {% else %}
                        <p>(Not Available)</p>
                        {% endif %}
                    </div>
                    <div style="width: 0px; height: 85%;border: 1px solid black;"></div>
                    <div class="info">
                        <img src="{{ url_for('static', filename='images/code-forces.png') }}" alt="">
                        {% if user.codeforces_username %}
                        <p>{{ user.codeforces_username }}</p>
                        {% else %}
                        <p>(Not Available)</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block head %}
<title>Sign Up</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/signup_style.css') }}" />
{% endblock %}

{% block body %}
<div class="out_box">
  <div class="in_box">
    <form method="POST">
      <input type="email" class="form-control" id="email" name="email" placeholder="E-mail" />
      <input type="username" class="form-control" id="username" name="username" placeholder="Username" />
      <input type="text" class="form-control" id="full_name" name="full_name" placeholder="Full Name" />
      <select name="gender" class="gender_combo">
        <option value="">Select Gender</option>
        <option value="Male">Male</option>
        <option value="Female">Female</option>
        <option value="Non-Binary">Non-Binary</option>
      </select>
      <input type="text" class="form-control" id="occupation" name="occupation" placeholder="(Optional) Occupation" />
      <input type="password" class="form-control" id="password" name="password1" placeholder="Password" />
      <input type="password" class="form-control" id="password" name="password2" placeholder="Confirm Password" />

      <button type="submit" class="btn">Login</button>
      <span style="margin-top: 30px">_____________________________</span>
    </form>
    <div class="sign_up">
      <span>Already have an account? </span><a href="/login">SIGN IN</a>
    </div>
  </div>
</div>
{% endblock %}